AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Five-Bullet Text Summariser – Lambda + Bedrock + S3

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 1024
    Timeout: 60
    Environment:
      Variables:
        MODEL_ID:  amazon.titan-text-lite-v1
        BUCKET_NAME: !Ref Bucket               # passed to handler

# ─────────────────────────── Resources ────────────────────────────
Resources:

  ## 1. HTTP API (CORS open for browser)
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: [POST, OPTIONS]
        AllowHeaders: [Content-Type]

  ## 2. S3 bucket for raw uploads + summaries
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-data"

  ## 3. Summariser Lambda (no S3 trigger now)
  Summariser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.lambda_handler

      # ---- permissions ----
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:          # read/write any object (avoids cycles)
            - Effect: Allow
              Action: [s3:GetObject, s3:PutObject]
              Resource: "arn:aws:s3:::*/*"
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: "*"

      # ---- API event sources ----
      Events:
        SummariseUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /summarise
            Method: post
        SummariseText:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /summarise-text
            Method: post

# ─────────────────────────── Outputs ─────────────────────────────
Outputs:
  BucketName:
    Description: S3 bucket holding raw uploads and summaries
    Value: !Ref Bucket

  ApiBaseUrl:
    Description: Invoke URL root for the HTTP API
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  SummariseTextUrl:
    Description: Convenience URL for POST /summarise-text
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/summarise-text"