AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Five-Bullet Summariser (S3 + URL)

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 1024
    Timeout: 30
    Environment:
      Variables:
        MODEL_ID: amazon.titan-text-lite-v1 # <─ titan text lite model ID

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-data"

  Summariser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.lambda_handler          # <─ our code path
      Policies:
        - AWSLambdaBasicExecutionRole             # write CloudWatch Logs
        - Statement:                              # generic S3 access
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: "arn:aws:s3:::*/*"
            - Effect: Allow                       # Bedrock call
              Action: bedrock:InvokeModel
              Resource: "*"
      Events:
        ## 1. S3 trigger (raw/ prefix)
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/
        ## 2. Public HTTP POST /summarise
        Api:
          Type: HttpApi
          Properties:
            Path:   /summarise
            Method: post

Outputs:
  BucketName:
    Description: S3 bucket to upload your .txt files (use the raw/ prefix)
    Value: !Ref Bucket
  ApiUrl:
    Description: Invoke URL for POST /summarise
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
